-- ==========================================
-- Supabase Database Schema — CollegeAI
-- ==========================================

-- 1. Create public.users table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NULL,
    auth_provider TEXT NOT NULL DEFAULT 'email',
    provider_user_id TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login TIMESTAMPTZ NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies if present
DROP POLICY IF EXISTS "Allow public registration" ON public.users;
DROP POLICY IF EXISTS "Allow user to view own record" ON public.users;
DROP POLICY IF EXISTS "Allow user to update own record" ON public.users;

-- 4. Create RLS Policies
CREATE POLICY "Allow public registration" 
ON public.users 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

CREATE POLICY "Allow user to view own record" 
ON public.users 
FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Allow user to update own record" 
ON public.users 
FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);
